# Generated by Django 5.0.1 on 2024-02-17 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('skillid', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=50, unique=True)),
                ('frequency', models.IntegerField()),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='user_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htnbackend.skills')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='htnbackend.users')),
            ],
            options={
                'db_table': 'user_skills',
            },
        ),
    ]
