# Generated by Django 5.0.1 on 2024-02-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htnbackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='frequency',
        ),
    ]
