# Generated by Django 5.0.1 on 2024-02-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htnbackend', '0002_remove_skills_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='frequency',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
